general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = ~/.config/hypr/scripts/wake.sh
}
listener {
    timeout = 120
    on-timeout = ~/.config/hypr/scripts/auto_lock.sh
    on-resume = ~/.config/hypr/scripts/wake.sh
}
